<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * lab3CMS
 * Lab3CMS - The CMS for web designers.
 * Simple and easy Content Management System developed for designers
 * Built on CodeIgniter - http://codeigniter.com
 *
 * @package	lab3CMS
 * @author	Pierre Silva - pierre.silva@lab3.com.co
 * @copyright	Copyright (c) 2013, Pierre Silva
 * @license	http://lab3.com.co/lab3cms/license
 * @link	http://lab3.com.co/lab3cms
 * @since	Version 1.0
 */
$config['site_email'] = "pierresilva@gmx.com";
$config['protocol'] = "smtp";
$config['mailpath'] = "/usr/sbin/sendmail";
$config['smtp_host'] = "smtp.gmx.com";
$config['smtp_user'] = "pierresilva@gmx.com";
$config['smtp_pass'] = "locombia1";
$config['smtp_port'] = "25";
$config['mailtype'] = "html";
$config['charset'] = "utf-8";
$config['wordwrap'] = TRUE;


/* End of file email.php */
/* Auto generated by Settings Administration on : 2013.04.02 17:33:03 */
/* Location: ./application/config/email.php */
